eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8002
spring:
  application:
    name: spring-cloud-consumer
  zipkin:
    base-url: http://192.168.31.51:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0
