eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000

spring:
  application:
    name: spring-cloud-zuul
  zipkin:
    base-url: http://192.168.31.51:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0

# 路由规则
zuul:
  routes:
    PROVIDER:
      path: /provider/**
      serviceId: spring-cloud-provider
    CONSUMER:
      path: /consumer/**
      serviceId: spring-cloud-consumer
