eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8001
spring:
  application:
    name: spring-cloud-provider
  zipkin:
    enabled: true
    base-url: http://192.168.31.51:9411
  sleuth:
    sampler:
      percentage: 1.0

